In [1]:
#1. Assign your Name to variable name and Age to variable age. 
#Make a Python program that prints your name and age.
name="Baskar"
age="19"
print("The name of the person is "+ name +" and his age is "+ age)

SyntaxError: invalid syntax (1567107993.py, line 1)

In [7]:
#X="Datascience is used to extract meaningful insights." 
#Split the string
X="Datascience is used to extract meaningful insights."
split_text=X.split()
print(split_text)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [14]:
#Make a function that gives multiplication of two numbers
def multiply(a,b):
    c=a*b
    print(c)
    
multiply(4,3)

12


In [18]:
#Create a Dictionary of 5 States with their capitals. also print the keys and values.
states_capital={"Tamilnadu":"Chennai","Karnataka":"Banglore","Kerala":"Thiruvananthapuram",
                "Maharashtra":"Mumbai","West Bengal":"Kolkata"}
print(states_capital)
print(states_capital.keys())
print(states_capital.values())
type(states_capital)

{'Tamilnadu': 'Chennai', 'Karnataka': 'Banglore', 'Kerala': 'Thiruvananthapuram', 'Maharashtra': 'Mumbai', 'West Bengal': 'Kolkata'}
dict_keys(['Tamilnadu', 'Karnataka', 'Kerala', 'Maharashtra', 'West Bengal'])
dict_values(['Chennai', 'Banglore', 'Thiruvananthapuram', 'Mumbai', 'Kolkata'])


dict

In [17]:
#Create a list of 1000 numbers using range function.
list_nos = [range(1000)]
list_nos
no = list(list_nos)
print(no)

[range(0, 1000)]


In [19]:
#Create an identity matrix of dimension 4 by 4
import numpy as np
matrix = np.eye(4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
#Create a 3x3 matrix with values ranging from 1 to 9
array1 = np.array([np.random.randint(1,9),np.random.randint(1,9),np.random.randint(1,9)])
array2 = np.array([np.random.randint(1,9),np.random.randint(1,9),np.random.randint(1,9)])
array3 = np.array([np.random.randint(1,9),np.random.randint(1,9),np.random.randint(1,9)])
# matrix = np.arange(1,10).reshape(3,3)
matrix = np.array([array1,array2,array3])
matrix

array([[5, 7, 5],
       [3, 7, 1],
       [1, 1, 7]])

In [21]:
#Given a dictionary, convert it into corresponding dataframe and display it
#dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
import pandas as pd
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
conversion = pd.DataFrame(dictionary)
print(dictionary)
print("-------------------------------------------------------------------------")
print(conversion)

{'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales': [250, 200, 240]}
-------------------------------------------------------------------------
     Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240


In [22]:
#Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)
# series_month = pd.Series(np.random.rand('2023-02-01'),('2023-03-02'))
date_series = pd.date_range(start='2023-02-01', end='2023-03-02',closed='left')
print(date_series)
date_list = date_series.strftime("%Y-%m-%d").tolist()
print(date_list)

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')
['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28', '2023-03-01']


/var/folders/q2/zp9bvrzd1v1gkt9fcfqkdnjm0000gn/T/ipykernel_11708/26838800.py:2: FutureWarning: Argument `closed` is deprecated in favor of `inclusive`.
  date_series = pd.date_range(start='2023-02-01', end='2023-03-02',closed='left')


In [ ]:
#Create 2 similar dimensional array and perform sum on them.
array1=np.array([10,50,100,150,200])
array2=np.array([20,30,70,80,100])
array3=(array1+array2)
print(np.ndim(array1))
print(np.ndim(array2))
print(array3)