In [1]:
# PROJECT DIABETES PREDICTION
# CLASSIFICATION PROBLEM 

In [2]:
# packages import 
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("diabetes_012_health_indicators_BRFSS2015.csv")

In [4]:
df.head()

Diabetes_012  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
0             0       1         1          1   40       1       0   
1             0       0         0          0   25       1       0   
2             0       1         1          1   28       0       0   
3             0       1         0          1   27       0       0   
4             0       1         1          1   24       0       0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                     0             0       0  ...              1   
1                     0             1       0  ...              0   
2                     0             0       1  ...              1   
3                     0             1       1  ...              1   
4                     0             1       1  ...              1   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  Age  Education  \
0            0        5        18        15         1    0    9          4   
1            1        3         0         0         0    0    7          6   
2            1        5        30        30         1    0    9          4   
3            0        2         0         0         0    0   11          3   
4            0        2         3         0         0    0   11          5   

   Income  
0       3  
1       1  
2       8  
3       6  
4       4  

[5 rows x 22 columns]

In [5]:
df.tail()

Diabetes_012  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
253675             0       1         1          1   45       0       0   
253676             2       1         1          1   18       0       0   
253677             0       0         0          1   28       0       0   
253678             0       1         0          1   23       0       0   
253679             2       1         1          1   25       0       0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
253675                     0             0       1  ...              1   
253676                     0             0       0  ...              1   
253677                     0             1       1  ...              1   
253678                     0             0       1  ...              1   
253679                     1             1       1  ...              1   

        NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  Age  \
253675            0        3         0         5         0    1    5   
253676            0        4         0         0         1    0   11   
253677            0        1         0         0         0    0    2   
253678            0        3         0         0         0    1    7   
253679            0        2         0         0         0    0    9   

        Education  Income  
253675          6       7  
253676          2       4  
253677          5       2  
253678          5       1  
253679          6       2  

[5 rows x 22 columns]

In [6]:
df.shape

(253680, 22)

In [7]:
# descriptive stats
df.describe()

Diabetes_012         HighBP       HighChol      CholCheck  \
count  253680.000000  253680.000000  253680.000000  253680.000000   
mean        0.296921       0.429001       0.424121       0.962670   
std         0.698160       0.494934       0.494210       0.189571   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       1.000000   
50%         0.000000       0.000000       0.000000       1.000000   
75%         0.000000       1.000000       1.000000       1.000000   
max         2.000000       1.000000       1.000000       1.000000   

                 BMI         Smoker         Stroke  HeartDiseaseorAttack  \
count  253680.000000  253680.000000  253680.000000         253680.000000   
mean       28.382364       0.443169       0.040571              0.094186   
std         6.608694       0.496761       0.197294              0.292087   
min        12.000000       0.000000       0.000000              0.000000   
25%        24.000000       0.000000       0.000000              0.000000   
50%        27.000000       0.000000       0.000000              0.000000   
75%        31.000000       1.000000       0.000000              0.000000   
max        98.000000       1.000000       1.000000              1.000000   

        PhysActivity         Fruits  ...  AnyHealthcare    NoDocbcCost  \
count  253680.000000  253680.000000  ...  253680.000000  253680.000000   
mean        0.756544       0.634256  ...       0.951053       0.084177   
std         0.429169       0.481639  ...       0.215759       0.277654   
min         0.000000       0.000000  ...       0.000000       0.000000   
25%         1.000000       0.000000  ...       1.000000       0.000000   
50%         1.000000       1.000000  ...       1.000000       0.000000   
75%         1.000000       1.000000  ...       1.000000       0.000000   
max         1.000000       1.000000  ...       1.000000       1.000000   

             GenHlth       MentHlth       PhysHlth       DiffWalk  \
count  253680.000000  253680.000000  253680.000000  253680.000000   
mean        2.511392       3.184772       4.242081       0.168224   
std         1.068477       7.412847       8.717951       0.374066   
min         1.000000       0.000000       0.000000       0.000000   
25%         2.000000       0.000000       0.000000       0.000000   
50%         2.000000       0.000000       0.000000       0.000000   
75%         3.000000       2.000000       3.000000       0.000000   
max         5.000000      30.000000      30.000000       1.000000   

                 Sex            Age      Education         Income  
count  253680.000000  253680.000000  253680.000000  253680.000000  
mean        0.440342       8.032119       5.050434       6.053875  
std         0.496429       3.054220       0.985774       2.071148  
min         0.000000       1.000000       1.000000       1.000000  
25%         0.000000       6.000000       4.000000       5.000000  
50%         0.000000       8.000000       5.000000       7.000000  
75%         1.000000      10.000000       6.000000       8.000000  
max         1.000000      13.000000       6.000000       8.000000  

[8 rows x 22 columns]

In [8]:
# checking for null values 

In [9]:
df.isnull().any()

Diabetes_012            False
HighBP                  False
HighChol                False
CholCheck               False
BMI                     False
Smoker                  False
Stroke                  False
HeartDiseaseorAttack    False
PhysActivity            False
Fruits                  False
Veggies                 False
HvyAlcoholConsump       False
AnyHealthcare           False
NoDocbcCost             False
GenHlth                 False
MentHlth                False
PhysHlth                False
DiffWalk                False
Sex                     False
Age                     False
Education               False
Income                  False
dtype: bool

In [10]:
df.isnull().sum()

Diabetes_012            0
HighBP                  0
HighChol                0
CholCheck               0
BMI                     0
Smoker                  0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
HvyAlcoholConsump       0
AnyHealthcare           0
NoDocbcCost             0
GenHlth                 0
MentHlth                0
PhysHlth                0
DiffWalk                0
Sex                     0
Age                     0
Education               0
Income                  0
dtype: int64

In [11]:
# no duplicate or missing values

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Diabetes_012          253680 non-null  int64
 1   HighBP                253680 non-null  int64
 2   HighChol              253680 non-null  int64
 3   CholCheck             253680 non-null  int64
 4   BMI                   253680 non-null  int64
 5   Smoker                253680 non-null  int64
 6   Stroke                253680 non-null  int64
 7   HeartDiseaseorAttack  253680 non-null  int64
 8   PhysActivity          253680 non-null  int64
 9   Fruits                253680 non-null  int64
 10  Veggies               253680 non-null  int64
 11  HvyAlcoholConsump     253680 non-null  int64
 12  AnyHealthcare         253680 non-null  int64
 13  NoDocbcCost           253680 non-null  int64
 14  GenHlth               253680 non-null  int64
 15  MentHlth              253680 non-n

In [13]:
df.head()

Diabetes_012  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
0             0       1         1          1   40       1       0   
1             0       0         0          0   25       1       0   
2             0       1         1          1   28       0       0   
3             0       1         0          1   27       0       0   
4             0       1         1          1   24       0       0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                     0             0       0  ...              1   
1                     0             1       0  ...              0   
2                     0             0       1  ...              1   
3                     0             1       1  ...              1   
4                     0             1       1  ...              1   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex  Age  Education  \
0            0        5        18        15         1    0    9          4   
1            1        3         0         0         0    0    7          6   
2            1        5        30        30         1    0    9          4   
3            0        2         0         0         0    0   11          3   
4            0        2         3         0         0    0   11          5   

   Income  
0       3  
1       1  
2       8  
3       6  
4       4  

[5 rows x 22 columns]

In [14]:
# drop unwanted columns
data = df.drop(columns=['Education','Income','Sex','NoDocbcCost'],axis=1)
data.head()

Diabetes_012  HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  \
0             0       1         1          1   40       1       0   
1             0       0         0          0   25       1       0   
2             0       1         1          1   28       0       0   
3             0       1         0          1   27       0       0   
4             0       1         1          1   24       0       0   

   HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  HvyAlcoholConsump  \
0                     0             0       0        1                  0   
1                     0             1       0        0                  0   
2                     0             0       1        0                  0   
3                     0             1       1        1                  0   
4                     0             1       1        1                  0   

   AnyHealthcare  GenHlth  MentHlth  PhysHlth  DiffWalk  Age  
0              1        5        18        15         1    9  
1              0        3         0         0         0    7  
2              1        5        30        30         1    9  
3              1        2         0         0         0   11  
4              1        2         3         0         0   11

In [15]:
# split into dependent and independent columns
y = data.iloc[:,0:1] # dependent variable 

In [16]:
y.head()

Diabetes_012
0             0
1             0
2             0
3             0
4             0

In [17]:
x = data.iloc[:,1:] # independent variables

In [18]:
x.head()

HighBP  HighChol  CholCheck  BMI  Smoker  Stroke  HeartDiseaseorAttack  \
0       1         1          1   40       1       0                     0   
1       0         0          0   25       1       0                     0   
2       1         1          1   28       0       0                     0   
3       1         0          1   27       0       0                     0   
4       1         1          1   24       0       0                     0   

   PhysActivity  Fruits  Veggies  HvyAlcoholConsump  AnyHealthcare  GenHlth  \
0             0       0        1                  0              1        5   
1             1       0        0                  0              0        3   
2             0       1        0                  0              1        5   
3             1       1        1                  0              1        2   
4             1       1        1                  0              1        2   

   MentHlth  PhysHlth  DiffWalk  Age  
0        18        15         1    9  
1         0         0         0    7  
2        30        30         1    9  
3         0         0         0   11  
4         3         0         0   11

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [21]:
#Model Building
from sklearn.tree import DecisionTreeClassifier

In [22]:
dt=DecisionTreeClassifier(criterion='entropy',random_state=0)
dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [23]:
pred1=dt.predict(x_test)
pred1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
#Model Building
from sklearn.neighbors import KNeighborsClassifier

In [25]:
knn=KNeighborsClassifier()

In [26]:
knn.fit(x_train,y_train)

C:\Users\nilas\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [27]:
pred2=knn.predict(x_test)
pred2

array([0, 0, 0, ..., 0, 0, 2], dtype=int64)

In [28]:
#Model Building
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()

In [29]:
nb.fit(x_train,y_train)
pred3=nb.predict(x_test)
pred3

C:\Users\nilas\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, ..., 0, 1, 2], dtype=int64)

In [30]:
#Model Building
from sklearn.ensemble import RandomForestClassifier

In [31]:
rf=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
rf.fit(x_train,y_train)

C:\Users\nilas\AppData\Local\Temp\ipykernel_12188\2519865731.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(x_train,y_train)


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [32]:
pred4=rf.predict(x_test)
pred4

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
#Model Building
from sklearn.linear_model import LogisticRegression

In [34]:
lr=LogisticRegression()

In [35]:
lr.fit(x_train,y_train)

C:\Users\nilas\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\nilas\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [36]:
pred5=lr.predict(x_test)

In [37]:
pred5

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [38]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [39]:
accuracy_score(y_test,pred1)*100 # Decision tree

78.87298959318827

In [40]:
confusion_matrix(y_test,pred1)

array([[37914,   708,  3995],
       [  671,    36,   201],
       [ 4901,   243,  2067]], dtype=int64)

In [41]:
print(classification_report(y_test,pred1))

              precision    recall  f1-score   support

           0       0.87      0.89      0.88     42617
           1       0.04      0.04      0.04       908
           2       0.33      0.29      0.31      7211

    accuracy                           0.79     50736
   macro avg       0.41      0.41      0.41     50736
weighted avg       0.78      0.79      0.78     50736



In [42]:
accuracy_score(y_test,pred2)*100 # KNN

83.1086408073163

In [43]:
confusion_matrix(y_test,pred2)

array([[40726,    36,  1855],
       [  778,     5,   125],
       [ 5758,    18,  1435]], dtype=int64)

In [44]:
print(classification_report(y_test,pred2))

              precision    recall  f1-score   support

           0       0.86      0.96      0.91     42617
           1       0.08      0.01      0.01       908
           2       0.42      0.20      0.27      7211

    accuracy                           0.83     50736
   macro avg       0.46      0.39      0.40     50736
weighted avg       0.79      0.83      0.80     50736



In [45]:
accuracy_score(y_test,pred3)*100 # Naieve Bayes

76.46641438032167

In [46]:
confusion_matrix(y_test,pred3)

array([[34714,   204,  7699],
       [  510,     3,   395],
       [ 3087,    45,  4079]], dtype=int64)

In [47]:
print(classification_report(y_test,pred3))

              precision    recall  f1-score   support

           0       0.91      0.81      0.86     42617
           1       0.01      0.00      0.01       908
           2       0.34      0.57      0.42      7211

    accuracy                           0.76     50736
   macro avg       0.42      0.46      0.43     50736
weighted avg       0.81      0.76      0.78     50736



In [48]:
accuracy_score(y_test,pred4)*100 # Random Forest

82.78736991485336

In [49]:
confusion_matrix(y_test,pred4)

array([[40389,   129,  2099],
       [  765,     9,   134],
       [ 5571,    35,  1605]], dtype=int64)

In [50]:
print(classification_report(y_test,pred4))

              precision    recall  f1-score   support

           0       0.86      0.95      0.90     42617
           1       0.05      0.01      0.02       908
           2       0.42      0.22      0.29      7211

    accuracy                           0.83     50736
   macro avg       0.44      0.39      0.40     50736
weighted avg       0.79      0.83      0.80     50736



In [51]:
accuracy_score(y_test,pred5)*100 # Logistic regression

84.31685588142543

In [52]:
confusion_matrix(y_test,pred5)

array([[41970,     0,   647],
       [  852,     0,    56],
       [ 6402,     0,   809]], dtype=int64)

In [53]:
print(classification_report(y_test,pred5))

              precision    recall  f1-score   support

           0       0.85      0.98      0.91     42617
           1       0.00      0.00      0.00       908
           2       0.54      0.11      0.19      7211

    accuracy                           0.84     50736
   macro avg       0.46      0.37      0.37     50736
weighted avg       0.79      0.84      0.79     50736



C:\Users\nilas\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nilas\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nilas\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [54]:
import pickle
pickle.dump(lr,open("model.pkl","wb"))

In [55]:
# testing model for diabetes
lr.predict([[1,1,1,40,1,0,0,0,0,1,0,1,5,18,15,1,10]])

C:\Users\nilas\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([2], dtype=int64)